Document: kylin-usb-creator
Title: Debian kylin-usb-creator Manual
Author: <insert document author here>
Abstract: This manual describes what kylin-usb-creator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kylin-usb-creator/kylin-usb-creator.sgml.gz

Format: postscript
Files: /usr/share/doc/kylin-usb-creator/kylin-usb-creator.ps.gz

Format: text
Files: /usr/share/doc/kylin-usb-creator/kylin-usb-creator.text.gz

Format: HTML
Index: /usr/share/doc/kylin-usb-creator/html/index.html
Files: /usr/share/doc/kylin-usb-creator/html/*.html
